server:
  port: 8080
spring:
  main:
    web-application-type: servlet
  application:
    name: batch
  quartz:
    job-store-type: jdbc
    scheduler-name: quartzScheduler
    jdbc:
      initialize-schema: always
    properties:
      org:
        quartz:
          jobStore:
            # 테이블 prefix 변경
            tablePrefix: QRTZ_
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/yugabyte
    username: yugabyte
    password: yugabyte
  jpa:
    hibernate:
      ddl-auto: create-drop
#    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true