server:
  port: 8080

spring:
  config:
    activate:
      on-profile: dev
  main:
    web-application-type: servlet
  application:
    name: batch
  quartz:
    job-store-type: jdbc
    scheduler-name: quartzScheduler
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO # 각 프로세스(인스턴스)에 고유 ID를 자동 부여
          threadPool:
            threadCount: 5 # 동시에 실행 가능한 Job 수(스레드 수)
            threadNamePrefix: QuartzScheduler
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore # JobStoreCMT를 상속받는 Spring wrapper
            #            class: org.quartz.impl.jdbcjobstore.JobStoreTX # 트랜잭션 제어 / 서버 환경 없이 애플리케이션 운영
            #            class: org.quartz.impl.jdbcjobstore.JobStoreCMT # 애플리케이션 서버 내에서 애플리케이션 운영 / 컨테이너가 트랜잭션 관리
            misfireThreshold: 6000 # 미스파이어 허용 오차(ms)
            isClustered: true
            # 테이블 prefix 변경
            tablePrefix: QRTZ_
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate

  datasource:
    yugabyte:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://172.17.0.1:5433/yugabyte
      username: yugabyte
      password: yugabyte
    postgres:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://172.17.0.1:5432/postgres
      username: postgres
      password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    #    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

logging:
  config: classpath:logback-${spring.config.activate.on-profile}.xml
  file:
    name: batch
    path: /data/log
    size: 10000 #10KB TRANSACTION log 사이즈
  level:
    root: INFO