DROP TABLE IF EXISTS BATCH_HIST_INFO;

CREATE TABLE BATCH_HIST_INFO
(
    ID             VARCHAR(255) NOT NULL,
    EXECUTION_TIME TIMESTAMP(6),
    DESCRIPTION    VARCHAR(255),
    JOB_CLASS_NM   VARCHAR(255),
    STTUS          VARCHAR(255),
    PRIMARY KEY (ID)
);